# Copyright (c) 2022 Andrea Cervesato <andrea.cervesato@suse.com>

name: "Static analysis"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - name: Show OS
      run: cat /etc/os-release

    - name: Git checkout
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: python3 -m pip install ruff pyrefly msgpack asyncssh

    - name: Test kirk
      run: ./kirk --help

    - name: Static Linting
      run: ruff check

    - name: Static type checking
      run: pyrefly check --project-excludes="*test*" libkirk
